version: '2'

services:
  web:
    build:
      context: .
    ports:
      - 80:80
      # - 443:443
      - 35729:35729 # LiveReload Common Port
    command: sh /init.sh
    volumes:
      - ./:/var/www/html
      - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/init.sh:/init.sh
      - ./docker/logs/apache2:/var/log/apache2
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: 123456

  redis:
    image: redis
    ports:
      - 6379:6379